### ISSUE TITLE
"unexpected status, the real value is Initialized" when doing test on several containers

### ISSUE THREAD

**Issue by carolwu-1206** [chaosblade-io/chaosblade-operator#55]
## Issue Description

Type: bug report

### Describe what happened (or what feature you want)
We send test request to blade server. The command is like 
```
create k8s container-network loss --percent 100 --interface eth0 --remote-port 3306 --container-ids 9ae406a853837f5ccfe4b8e34089e0ec221ad9fb441389b0d71332b5f1f7b25d,b0e9875d7bdcdae23dc05fed80e1654a72f39bccbf2e9c5dfa471eebcb09b82b --namespace integrationspublisher --timeout 1800 --names integrations-publisher-svc-6b66c984d8-h8lg7,integrations-publisher-svc-6b66c984d8-wvrrt --kubeconfig ~/.kube/config
```
After 20 seconds, we get the response ```unexpected status, the real value is Initialized```. However, when we check the blade status by "kubectl describe blade xxxxxxxx", it has started successfully.
```
status:
  expStatuses:
  - action: loss
    resStatuses:
    - id: 372d900cb84c87d6
      identifier: integrationspublisher/stagenode01/integrations-publisher-svc-6b66c984d8-h8lg7/integrations-publisher-svc/9ae406a85383
      kind: container
      state: Success
      success: true
    - id: 6f32cd396e4a2ebd
      identifier: integrationspublisher/stagenode01/integrations-publisher-svc-6b66c984d8-wvrrt/integrations-publisher-svc/b0e9875d7bdc
      kind: container
      state: Success
      success: true
    scope: container
    state: Success
    success: true
    target: network
  phase: Running
```

Then we tried to start test on one container, and everything went well. 

### Describe what you expected to happen

Test can be started when there is several container and the response is success.

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Tell us your environment
Chaosblade 0.9.0
